server {
    listen 80;
    listen [::]:80;
    server_name illinoislotterytracker.com www.illinoislotterytracker.com;

    server_tokens off;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/illinoislotterytracker;
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        return 301 https://scratchoffdata.com$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name www.illinoislotterytracker.com;

    ssl_certificate /etc/letsencrypt/live/illinoislotterytracker.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/illinoislotterytracker.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    server_tokens off;
    return 301 https://scratchoffdata.com$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name illinoislotterytracker.com;

    ssl_certificate /etc/letsencrypt/live/illinoislotterytracker.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/illinoislotterytracker.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    server_tokens off;
    return 301 https://scratchoffdata.com$request_uri;
}
